package supton.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2014-10-29 23:51:53 by Hibernate Tools 3.4.0.CR1

/**
 * Organization generated by hbm2java
 */
@Entity  
@Table(name = "organization")
public class Organization implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	private String parentcode;
	//1，机构，2，现金库，3，款包库，4凭证库
	private Integer type;
	private String name;
	private String alias;
	private String address;
	private String telephone;
	private String manager;
	private String cellphone;
	private String tid;
	private Integer tusernum;

	// Constructors

	/** default constructor */
	public Organization() {
	}

	/** full constructor */
	public Organization(String code, String parentcode, Integer type,
			String name, String alias, String address, String telephone,
			String manager, String cellphone, String tid, Integer tusernum) {
		this.code = code;
		this.parentcode = parentcode;
		this.type = type;
		this.name = name;
		this.alias = alias;
		this.address = address;
		this.telephone = telephone;
		this.manager = manager;
		this.cellphone = cellphone;
		this.tid = tid;
		this.tusernum = tusernum;
	}

	// Property accessors
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "parentcode", length = 30)
	public String getParentcode() {
		return this.parentcode;
	}

	public void setParentcode(String parentcode) {
		this.parentcode = parentcode;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "alias", length = 50)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "manager", length = 30)
	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Column(name = "cellphone", length = 50)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "tid", length = 30)
	public String getTid() {
		return this.tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	/**
	 * @return the tusernum
	 */
	@Column(name = "tusernum")
	public Integer getTusernum() {
		return tusernum;
	}

	/**
	 * @param tusernum the tusernum to set
	 */
	public void setTusernum(Integer tusernum) {
		this.tusernum = tusernum;
	}

}