package supton.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

// Generated 2014-10-29 23:51:53 by Hibernate Tools 3.4.0.CR1

/**
 * Role generated by hbm2java
 */
@Entity  
@Table(name = "role")
public class Role implements java.io.Serializable {

	// Fields

	private Integer id;
	private String code;
	//type：1为正常岗位，2为不相容岗位
	private Integer type;
	private String name;
	private String alias;
	private List<Rolefunction> rolefunctionList;

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** full constructor */
	public Role(String code, Integer type, String name, String alias) {
		this.code = code;
		this.type = type;
		this.name = name;
		this.alias = alias;
	}

	// Property accessors
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "code", length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	
	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "alias", length = 50)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Transient
	public List<Rolefunction> getRolefunctionList() {
		return rolefunctionList;
	}

	public void setRolefunctionList(List<Rolefunction> rolefunctionList) {
		this.rolefunctionList = rolefunctionList;
	}

}
